import 'package:json_annotation/json_annotation.dart';

import 'game_fill_blank_model.dart';

part 'game_pick_sentence_model.g.dart'; // This file is generated by json_serializable

@JsonSerializable()
class GamePickSentenceDTO {
  final int id;
  final LanguageDTO? language;
  final ContextImageDTO? contextImage;
  final List<String> answers;
  final String? answerSentence;

  GamePickSentenceDTO({
    required this.id,
    this.language,
    this.contextImage,
    required this.answers,
    this.answerSentence,
  });

  factory GamePickSentenceDTO.fromJson(Map<String, dynamic> json) =>
      _$GamePickSentenceDTOFromJson(json);
  Map<String, dynamic> toJson() => _$GamePickSentenceDTOToJson(this);
}
